- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/dotfiles.yml
