- name: Install System Packages
  become: true
  apt:
    name:
      ["build-essential", "ninja-build", "gettext", "cmake", "unzip", "curl", "ripgrep", "fd-find"]
  tags:
    - install
    - neovim
    - core
