- name: Ensure the config folder exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config" 
    state: directory
  tags:
    - install
    - dotfiles

- name: Check if nvim folder exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/nvim"
  register: nvim_folder
  tags:
    - install
    - dotfiles

- name: Clone nvim config
  ansible.builtin.git:
    repo: https://github.com/lorrandavid/kickstart.nvim
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    version: master
  when: not nvim_folder.stat.exists
  tags:
    - install
    - dotfiles
