- name: Get current timestamp
  command: date +"%Y%m%d%H%M%S"
  register: timestamp_result
  changed_when: false

- name: Create backup to old Neovim config
  shell: "mv {{ lookup('env', 'HOME') }}/.config/nvim {{ lookup('env', 'HOME') }}/.config/nvim_{{ timestamp_result.stdout }}.bak"
  ignore_errors: yes
  tags:
    - install
    - dotfiles

- name: Create symlink to Neovim config
  file:
    src: "{{ lookup('env', 'PWD') }}/nvim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: link
    force: yes
  tags:
    - install
    - dotfiles
