- name: Get current timestamp
  command: date +"%Y%m%d%H%M%S"
  register: timestamp_result
  changed_when: false
  tags:
    - install
    - dotfiles
    - terminal

- name: Ensure the config folder exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config" 
    state: directory
  tags:
    - install
    - dotfiles

- name: Check if nvim folder exists
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
  register: nvim_folder
  tags:
    - install
    - dotfiles

- name: Create backup of old Neovim config
  shell: "mv {{ lookup('env', 'HOME') }}/.config/nvim {{ lookup('env', 'HOME') }}/.config/nvim_{{ timestamp_result.stdout }}.bak"
  when: nvim_folder.stat.exists
  ignore_errors: yes
  tags:
    - install
    - dotfiles

- name: Clone nvim config
  ansible.builtin.git:
    repo: https://github.com/lorrandavid/kickstart.nvim
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    version: main
    force: yes
  tags:
    - install
    - dotfiles
