- name: Check nvm installation
  stat:
    path: "{{ lookup('env', 'HOME') }}/.nvm"
  register: nvm_stats
  tags:
    - install
    - node

- name: Install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"
  tags:
    - install
    - node
  when: nvm_stats.stat.exists == False

- name: Install Node.js LTS
  become: no
  shell: >
    . {{ lookup('env', 'HOME') }}/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
    chdir: "{{ lookup('env', 'HOME') }}"
    creates: "{{ lookup('env', 'HOME') }}/.nvm/versions/node"
  tags:
    - install
    - node
  when: nvm_stats.stat.exists == False
