- name: Install Yarn
  npm:
    name: yarn
    global: yes
  tags:
    - install
    - node

- name: Install Http-server
  npm:
    name: http-server
    global: yes
  tags:
    - install
    - node

- name: Install tsserver
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - install
    - node
