- name: Install Yarn if not already installed
  shell: "npm list -g yarn || npm install -g yarn"
  register: yarn_installed
  changed_when: yarn_installed.rc != 0
  tags:
    - install
    - node

- name: Install Http-server if not already installed
  shell: "npm list -g http-server || npm install -g http-server"
  register: http_server_installed
  changed_when: http_server_installed.rc != 0
  tags:
    - install
    - node

- name: Install tsserver if not already installed
  shell: "npm list -g typescript-language-server || npm install -g typescript-language-server"
  register: tsserver_installed
  changed_when: tsserver_installed.rc != 0
  tags:
    - install
    - node

- name: Install bun if not already installed
  shell: "npm list -g bun || npm install -g bun"
  register: bun_installed
  changed_when: bun_installed.rc != 0
  tags:
    - install
    - node

- name: Install pnpm if not already installed
  shell: "npm list -g pnpm || npm install -g pnpm"
  register: pnpm_installed
  changed_when: pnpm_installed.rc != 0
  tags:
    - install
    - node

