# Alacritty Configuration for Windows
working_directory = "C:\\Users\\Lorran"

# Window configuration
[window]
dynamic_padding = true
decorations = "full"

[window.padding]
x = 6
y = 0

# Font configuration
[font]
size = 12
offset.x = 0
offset.y = 4

[font.normal]
family = "ZedMono Nerd Font"
style = "Extended"

[font.bold]
family = "ZedMono Nerd Font"
style = "Medium"

[font.italic]
family = "ZedMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "ZedMono Nerd Font"
style = "Bold Italic"

# Shell configuration
[shell]
program = "pwsh"
args = ["-NoLogo"]

# Colors (Tokyo Night) https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = "0x222436"
foreground = "0xc8d3f5"

# Normal colors
[colors.normal]
black = "0x1b1d2b"
red = "0xff757f"
green = "0xc3e88d"
yellow = "0xffc777"
blue = "0x82aaff"
magenta = "0xc099ff"
cyan = "0x86e1fc"
white = "0x828bb8"

# Bright colors
[colors.bright]
black = "0x444a73"
red = "0xff757f"
green = "0xc3e88d"
yellow = "0xffc777"
blue = "0x82aaff"
magenta = "0xc099ff"
cyan = "0x86e1fc"
white = "0xc8d3f5"

# Cursor style
[cursor]
blink_interval = 750

[cursor.style]
shape = "Block"
blinking = "On"

# Key bindings
[keyboard]
bindings = [
  { key = "V",         mods = "Control|Shift", action = "Paste"            },
  { key = "C",         mods = "Control|Shift", action = "Copy"             },
  { key = "Insert",    mods = "Shift",         action = "PasteSelection"   },
  { key = "Key0",      mods = "Control",       action = "ResetFontSize"    },
  { key = "Equals",    mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",     mods = "Control",       action = "DecreaseFontSize" },
]
